export const SRS_INTERVALS=[1,3,7,21],SPEED_TARGET=90;
export function localDateKey(value=new Date()){const d=value instanceof Date?value:new Date(value);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function addLocalDays(key,days){const[y,m,d]=key.split('-').map(Number);return localDateKey(new Date(y,m-1,d+days))}
export function daysBetween(a,b){const p=s=>s.split('-').map(Number),x=p(a),y=p(b);return Math.round((Date.UTC(x[0],x[1]-1,x[2])-Date.UTC(y[0],y[1]-1,y[2]))/86400000)}
export function updateSrs(record,correct,today=localDateKey(),attempt={}){const old=record||{stage:0,due:today,streak:0,history:[]},history=[...(old.history||[]),{date:today,correct,...attempt}];if(!correct)return{stage:1,due:addLocalDays(today,1),streak:0,history};if(!record)return null;if(old.stage===21&&old.streak>=1)return{...old,graduated:true,graduatedAt:today,streak:old.streak+1,history};const i=Math.max(0,SRS_INTERVALS.indexOf(old.stage)),stage=SRS_INTERVALS[Math.min(i+1,3)];return{stage,due:addLocalDays(today,stage),streak:old.streak+1,history}}
export function queueBuckets(srs,today=localDateKey()){const b={today:0,tomorrow:0,3:0,7:0,21:0};Object.values(srs||{}).filter(r=>r&&!r.graduated).forEach(r=>{const d=daysBetween(r.due,today);if(d<=0)b.today++;else if(d===1)b.tomorrow++;else if([3,7,21].includes(d))b[d]++});return b}
export function dueIds(srs,today=localDateKey()){return Object.entries(srs||{}).filter(([,r])=>r&&!r.graduated&&daysBetween(r.due,today)<=0).map(([id])=>id)}
export function classifyQuestion(q){return q.figures?.length?'image':(q.stem||'').length>=120?'long':'general'}
export const TYPE_LABELS={image:'影像判讀題',long:'長題幹臨床情境',general:'一般題'};
export function speedStats(attempts,qmap){const g={image:{n:0,c:0,s:0},long:{n:0,c:0,s:0},general:{n:0,c:0,s:0}};(attempts||[]).forEach(a=>{const q=qmap.get(a.id);if(!q)return;const x=g[classifyQuestion(q)];x.n++;x.c+=a.correct?1:0;x.s+=Number(a.seconds)||0});return Object.entries(g).map(([type,x])=>({type,label:TYPE_LABELS[type],n:x.n,average:x.n?Math.round(x.s/x.n):0,rate:x.n?Math.round(x.c/x.n*100):0,slowButAccurate:x.n>0&&x.s/x.n>SPEED_TARGET&&x.c/x.n>=.6}))}
export function subjectStats(attempts){const g={};(attempts||[]).forEach(a=>{const k=a.specialty||a.subject||'尚未分類';g[k]??={n:0,c:0,s:0};g[k].n++;g[k].c+=a.correct?1:0;g[k].s+=Number(a.seconds)||0});return Object.entries(g).map(([name,x])=>({name,n:x.n,rate:Math.round(x.c/x.n*100),average:Math.round(x.s/x.n)})).sort((a,b)=>a.rate-b.rate||b.n-a.n)}
export function buildDailyPlan({questions,attempts,srs,examDate,today=localDateKey()}){const seen=new Set((attempts||[]).map(a=>a.id)),unseen=questions.filter(q=>!seen.has(q.id)),remainingDays=Math.max(1,daysBetween(examDate,today)),daily=Math.min(80,Math.max(10,Math.ceil(unseen.length/remainingDays))),reviewIds=dueIds(srs,today),slots=Math.max(0,daily-reviewIds.length),stats=subjectStats(attempts),attack=Math.ceil(slots*.6);return{today,examDate,remainingDays,unseen:unseen.length,daily,total:reviewIds.length+slots,review:reviewIds.length,reviewIds,attack,maintain:slots-attack,weak:stats[0]?.name||'尚未有作答資料',strong:stats.at(-1)?.name||'綜合科目'}}
export function fcKey(ref){return ref?JSON.stringify([ref.volume||ref.book||ref['冊別']||'',ref.chapter||ref['章節']||ref.specialty||'',ref.page||ref['頁次']||'']):null}
